# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 234f6b0e4a0b8aad7361b84e6126f972cd050626d02a80472dc670b89e5907a018d5a1ca858f8b281ae6bff16441a314547644768af84f3fb8b874526d4f3118

test:
  secret_key_base: 704f97501317e7b85b222ee33671688a7771c430f84efe5104fc27aceff404de1cc77a750807af56663eb3215a8f09e33171ea3a360e315f6dbab510bff8886c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
